from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
INSTANCE_FOLDER = PROJECT_ROOT / "instances"
OUTPUT_FOLDER = PROJECT_ROOT / "outputs"
DATA_FOLDER = PROJECT_ROOT / "data"
DATASETS_FOLDER = DATA_FOLDER / "datasets"
MODELS_FOLDER = PROJECT_ROOT / "models"
HYPERPARAMETERS_FOLDER = MODELS_FOLDER / "hyperparams"
EXPERIMENTS_FOLDER = PROJECT_ROOT / "experiments"

BSG_SOLVER_PATH = PROJECT_ROOT / "BSG_CLP"
VCS_SOLVER_PATH = PROJECT_ROOT / "VCS"